packages:
  - generators/**
onlyBuiltDependencies:
  - '@apollo/protobufjs'
  - '@nestjs/core'
  - '@parcel/watcher'
  - '@prisma/client'
  - '@prisma/engines'
  - '@prisma/extension-optimize'
  - '@swc/core'
  - '@tailwindcss/oxide'
  - core-js
  - esbuild
  - graphql-query-complexity
  - graphql-redis-subscriptions
  - ioredis
  - nx
  - pluralize
  - prisma
  - prisma-graphql-type-decimal
  - type-graphql
