import { Client } from 'pg';
export declare const MAX_RETRIES = 30;
export declare const WORKSPACE_NAME: string;
export declare const DATABASE_URL: string;
export declare const DOCKER_COMPOSE_FILE = ".dev/docker-compose.yml";
export declare function log(...msg: any[]): void;
export declare function connectToPostgres(url: string): Promise<Client>;
export declare function canConnect(url: string): Promise<boolean>;
export declare function ensureDockerIsRunning(): boolean;
export declare function isDockerComposeRunning(): boolean;
export declare function ensureDockerComposeIsRunning(): Promise<boolean>;
export declare function ensureDotEnv(): void;
export declare function runPrismaSetup(): boolean;
export declare function runPrismaSeed(): boolean;
export declare function runGraphQLTypeGeneration(): boolean;
export declare const sleep: (ms?: number) => Promise<unknown>;
